CREATE TABLE Users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE Events (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	event_name TEXT NOT NULL,
	event_date DATETIME NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES Users(id)
);